name: CI workflow
on: [push, pull_request]

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Compile and Test
      run: ./gradlew build

    - name: Upload JAR
      uses: actions/upload-artifact@v3
      with:
          name: rsyncit-jar
          path: build/libs/rsyncit-0.0.1-SNAPSHOT.jar


  docker:
    runs-on: ubuntu-latest
    needs: gradle-build
#    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: checkout sources
        uses: actions/checkout@v3

      - name: Fetch jar
        uses: actions/download-artifact@v3
        with:
          name: rsyncit-jar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build_rsyncit
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ripencc/rsyncit:latest
          labels: "org.label-schema.vcs-ref=${{ github.sha }}"
          build-args: |
            JAR_FILE=build/libs/rsyncit-0.0.1-SNAPSHOT.jar            

      - name: Image digest
        run: echo ${{ steps.docker_build_rsyncit.outputs.digest }}