name: CI workflow
on: [push, pull_request]

jobs:
  gradle-build:
    uses: ./.github/workflows/gradle-build.yml

  docker:
    uses: ./.github/workflows/docker.yml
    needs: gradle-build
    with:
      jar-artifact: rsyncit-jar
      tags: ghcr.io/ripe-ncc/rsyncit:latest
      push: ${{ github.ref == 'refs/heads/main' }}
