name: docker
on:
  workflow_call:
    inputs:
      jar-artifact:
        description: "Name of the executable JAR artifact to download."
        type: string
        required: true
      push:
        description: "Whether to push the image."
        type: boolean
        required: true
        default: false
      tags:
        description: "Image tags (comma separated) to build and push"
        type: string
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout sources
        uses: actions/checkout@v3

      - name: Fetch jar
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.jar-artifact }}
          path: rsyncit.jar

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Build
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        id: docker_build_rsyncit
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ inputs.tags }}
          labels: "org.label-schema.vcs-ref=${{ github.sha }}"
          build-args: |
            JAR_FILE=rsyncit.jar   

      - name: Image digest
        run: echo ${{ steps.docker_build_rsyncit.outputs.digest }}
