name: Gradle build and test
on:
  workflow_call:
    outputs:
      jar-artifact:
        description: "Name of the executable JAR artifact."
        value: "rsyncit-jar"
      test-reports:
        description: "Name of the test reports artifact."
        value: "test-reports"

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Compile and Test
        run: ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: rsyncit-jar
          path: build/libs/rsyncit-*.jar