name: Release
on:
  release:
    types: [ "published" ]

jobs:
  gradle-build:
    uses: ./.github/workflows/gradle-build.yml

  docker:
    uses: ./.github/workflows/docker.yml
    needs: gradle-build
    with:
      jar-artifact: ${{ needs.gradle-build.outputs.jar-artifact }}
      push: true
      tags: ghcr.io/ripe-ncc/rsyncit:${{ github.event.release.tag_name }}, ghcr.io/ripe-ncc/rsyncit:latest
